name: "Test"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v15
      with:
        name: notlebedev
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check --print-build-logs
